version: "3.9"
services:
  # 1. База данных (InfluxDB)
  influxdb:
    image: influxdb:2.7-alpine
    container_name: marits-influxdb
    restart: unless-stopped
    volumes:
      - ./infra/influxdb/data:/var/lib/influxdb2
    environment: #Переменные DOCKER_INFLUXDB_INIT_* работают только при первом запуске
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
      - INFLUXD_LOG_LEVEL=error
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider -q http://localhost:8086/health"]
      # или через curl, если он есть в образе:
      # test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metrics-net

  # 2. Сервер, пишущий в Influx
  metrics_server:
    restart: unless-stopped
    build:
      context: ./services/metrics_server
    container_name: marits-metrics-server
    depends_on:
      influxdb:
        condition: service_healthy
    ports:
      - "8888:8888"    
    environment:
      - INFLUX_USER=${INFLUX_USER}
      - INFLUX_PASS=${INFLUX_PASS}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      # - INFLUX_URL=influxdb
      - INFLUX_URL=http://influxdb:8086
    networks:
      - metrics-net

  # 3. FastAPI-обёртка (основной сервис)
  metrics_client_api:
    restart: unless-stopped
    build:
      context: ./services/metrics_client_api
    container_name: marits-metrics-api
    environment:
      METRICS_SERVER_HOST: metrics_server
      METRICS_SERVER_PORT: "8888"
    ports:
      - "8000:8000"
    depends_on:
      - metrics_server
    networks:
      - metrics-net

  # 4. Агент мониторинга (Читает ОС)
  cpu_monitor:
    build:
      context: ./services/cpu_monitor
    container_name: marits-cpu-monitor
    depends_on:
      - metrics_client_api
    networks:
      - metrics-net
    environment:
      METRICS_API_URL: http://metrics_client_api:8000
      CPU_SCRAPE_INTERVAL: "5.0"
      CPU_COMPRESSOR: "none"

  # 5. Marimo Тетрадка
  marimo_dashboard:
    build:
      context: ./services/marimo_dashboard
    container_name: marits-marimo
    volumes:
      - ./services/marimo_dashboard/notebooks:/app/notebooks
    ports:
      - "8080:8080"
    networks:
      - metrics-net
    environment:
      METRICS_CLIENT_API_HOST: metrics_client_api
      METRICS_CLIENT_API_PORT: "8000"
    depends_on:
      - metrics_client_api

  # 6. JS-Фронтенд
  web_dashboard:
    restart: unless-stopped
    build:
      context: ./services/web_dashboard
    container_name: marits-web-ui
    # МОНТИРУЕМ КОД ДЛЯ ХОТ-РЕЛОАДА
    #volumes:
    #  - ./services/metrics_client_api/src:/app/src
    ports:
      - "4000:4000"
    environment:
      METRICS_API_BASE: http://metrics_client_api:8000
      WEB_DASHBOARD_HOST: 0.0.0.0
      WEB_DASHBOARD_PORT: "4000"
      # Отключаем создание кеша .pyc внутри контейнера
      #PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - metrics_client_api
    # ПЕРЕОПРЕДЕЛЯЕМ КОМАНДУ ДЛЯ РАЗРАБОТКИ
    #command: ["uvicorn", "metrics_client_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - metrics-net

networks:
  metrics-net:
    driver: bridge